import React, { useState } from 'react';
import { Terminal, Copy, Check, Play, FileCode, Cpu } from 'lucide-react';

interface ScriptTemplate {
  id: string;
  name: string;
  filename: string;
  lang: 'bash' | 'javascript' | 'markdown';
  description: string;
  content: string;
  simulatedOutput: string;
}

const SCRIPTS: ScriptTemplate[] = [
  {
    id: 'create-pr-script',
    name: 'Octokit Agent PR Creator',
    filename: 'scripts/create-agent-pr.mjs',
    lang: 'javascript',
    description: 'Automated script for agents to authenticate, branch, commit, and open PRs.',
    content: `#!/usr/bin/env node
import { Octokit } from "@octokit/rest";
import { createAppAuth } from "@octokit/auth-app";

const {
  GITHUB_APP_ID,
  GITHUB_APP_PRIVATE_KEY,
  GITHUB_APP_INSTALLATION_ID,
  TARGET_REPO = "jbatt2026/AI-AGENTS",
  BRANCH_NAME = "agent/claude-update",
  PR_TITLE = "feat: automated agent enhancement",
  PR_BODY = "Automated updates generated by AI Agent.\\n\\n> Generated with [Claude Code](https://claude.ai/code)",
} = process.env;

async function main() {
  console.log("🤖 Authenticating AI Agent with GitHub App...");
  const [owner, repo] = TARGET_REPO.split("/");

  const octokit = new Octokit({
    authStrategy: createAppAuth,
    auth: {
      appId: GITHUB_APP_ID,
      privateKey: GITHUB_APP_PRIVATE_KEY,
      installationId: GITHUB_APP_INSTALLATION_ID,
    },
  });

  // Get base commit
  const { data: baseRef } = await octokit.rest.git.getRef({
    owner,
    repo,
    ref: "heads/main",
  });

  console.log(\`🌿 Creating branch: \${BRANCH_NAME} from \${baseRef.object.sha.slice(0, 7)}\`);
  await octokit.rest.git.createRef({
    owner,
    repo,
    ref: \`refs/heads/\${BRANCH_NAME}\`,
    sha: baseRef.object.sha,
  });

  console.log("📝 Submitting Pull Request...");
  const pr = await octokit.rest.pulls.create({
    owner,
    repo,
    title: PR_TITLE,
    head: BRANCH_NAME,
    base: "main",
    body: PR_BODY,
  });

  console.log(\`✅ PR successfully opened: \${pr.data.html_url}\`);
}

main().catch((err) => {
  console.error("❌ Agent PR creation failed:", err.message);
  process.exit(1);
});`,
    simulatedOutput: `🤖 Authenticating AI Agent with GitHub App...
🔑 Obtained short-lived installation access token (ghs_***)
🌿 Creating branch: agent/claude-update from 9a41df2
📝 Submitting Pull Request...
✅ PR successfully opened: https://github.com/jbatt2026/AI-AGENTS/pull/2`,
  },
  {
    id: 'verify-secrets',
    name: 'Secret Leak Detector',
    filename: 'scripts/verify-secrets.sh',
    lang: 'bash',
    description: 'Pre-push and CI check ensuring no .pem or private keys are accidentally committed.',
    content: `#!/usr/bin/env bash
set -e

echo "🔍 Scanning repository for private keys, .pem files, and hardcoded tokens..."

LEAK_COUNT=0

# Scan for private RSA keys
if grep -rn "BEGIN RSA PRIVATE KEY" . --exclude-dir={node_modules,.git,dist} 2>/dev/null; then
  echo "❌ CRITICAL: Found RSA private key in committed files!"
  LEAK_COUNT=$((LEAK_COUNT + 1))
fi

# Scan for committed .pem files
if find . -name "*.pem" -not -path "*/node_modules/*" | grep -q .; then
  echo "❌ CRITICAL: Found .pem file in repository tree!"
  LEAK_COUNT=$((LEAK_COUNT + 1))
fi

if [ $LEAK_COUNT -gt 0 ]; then
  echo "🚫 Secret check failed! Remove sensitive credentials before committing."
  exit 1
else
  echo "✅ No secret leaks detected. Repository is clean!"
fi`,
    simulatedOutput: `🔍 Scanning repository for private keys, .pem files, and hardcoded tokens...
✅ Checked RSA signatures
✅ Checked .pem extensions
✅ Checked .env files
✅ No secret leaks detected. Repository is clean!`,
  },
  {
    id: 'claude-agent-prompt',
    name: 'Claude Code Agent Prompt Template',
    filename: 'docs/AGENT_PROMPT.md',
    lang: 'markdown',
    description: 'Standard prompt instructions provided to autonomous AI agents working in this repo.',
    content: `## Instructions for AI Agents in jbatt2026/AI-AGENTS

1. Scope: Read CLAUDE.md before proposing or executing changes.
2. Branching: Always branch from 'main' with the prefix 'agent/<agent-name>-<slug>'.
3. Testing: Run \`npm run build\` and ensure zero syntax or type errors before opening PR.
4. Attribution: Always append the standard Claude Code attribution footer:
   > Generated with [Claude Code](https://claude.ai/code) / [AI-AGENTS](https://github.com/jbatt2026/AI-AGENTS)
   > Co-Authored-By: Claude <noreply@anthropic.com>
5. Secrets: Never output or commit RSA private keys, tokens, or .env secrets.`,
    simulatedOutput: `✅ Agent Prompt Template loaded into agent context buffer. Ready for autonomous tasks.`,
  },
];

export const AgentScriptsRunner: React.FC = () => {
  const [selectedScriptId, setSelectedScriptId] = useState<string>('create-pr-script');
  const [copied, setCopied] = useState(false);
  const [running, setRunning] = useState(false);
  const [output, setOutput] = useState<string>('');

  const currentScript = SCRIPTS.find((s) => s.id === selectedScriptId) || SCRIPTS[0];

  const handleRun = async () => {
    setRunning(true);
    setOutput('Starting script execution...\n');
    await new Promise((r) => setTimeout(r, 600));
    setOutput(currentScript.simulatedOutput);
    setRunning(false);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(currentScript.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-6">
      {/* Top Banner */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-sm">
        <div className="flex items-center space-x-3">
          <Cpu className="w-6 h-6 text-blue-400" />
          <div>
            <h2 className="text-lg font-bold text-white">Agent Scripts & Automation Tools</h2>
            <p className="text-sm text-slate-400 mt-1">
              Pre-built scripts and execution runners that empower autonomous AI agents (Hermes, Claude Code, Gemini) to automate code management.
            </p>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left: Script Selector */}
        <div className="lg:col-span-4 space-y-4">
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-3">
            <h3 className="text-sm font-semibold text-slate-200 uppercase tracking-wider">
              Available Tools
            </h3>

            <div className="space-y-2">
              {SCRIPTS.map((script) => {
                const isSelected = selectedScriptId === script.id;
                return (
                  <button
                    key={script.id}
                    onClick={() => {
                      setSelectedScriptId(script.id);
                      setOutput('');
                    }}
                    className={`w-full text-left p-3.5 rounded-lg border transition-all ${
                      isSelected
                        ? 'bg-blue-950/40 border-blue-500/50 shadow-sm'
                        : 'bg-slate-950 border-slate-800 hover:border-slate-700'
                    }`}
                  >
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-semibold text-slate-200">{script.name}</span>
                      <span className="text-[10px] px-1.5 py-0.5 rounded bg-slate-800 text-blue-300 font-mono">
                        {script.lang}
                      </span>
                    </div>
                    <p className="text-[11px] text-slate-400 mt-1 font-mono">{script.filename}</p>
                    <p className="text-[11px] text-slate-500 mt-1 line-clamp-2">{script.description}</p>
                  </button>
                );
              })}
            </div>
          </div>
        </div>

        {/* Right: Code Viewer & Interactive Terminal */}
        <div className="lg:col-span-8 space-y-4">
          {/* Script Code Viewer */}
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-3">
            <div className="flex items-center justify-between pb-3 border-b border-slate-800">
              <div className="flex items-center space-x-2">
                <FileCode className="w-4 h-4 text-blue-400" />
                <span className="text-xs font-mono font-semibold text-slate-200">
                  {currentScript.filename}
                </span>
              </div>

              <div className="flex items-center space-x-2">
                <button
                  onClick={handleCopy}
                  className="px-2.5 py-1 text-xs font-medium text-slate-300 bg-slate-800 hover:bg-slate-700 rounded-lg border border-slate-700 inline-flex items-center space-x-1 transition-colors"
                >
                  {copied ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                  <span>{copied ? 'Copied' : 'Copy'}</span>
                </button>
                <button
                  onClick={handleRun}
                  disabled={running}
                  className="px-3 py-1 text-xs font-semibold text-white bg-blue-600 hover:bg-blue-500 rounded-lg shadow-sm inline-flex items-center space-x-1.5 transition-colors"
                >
                  <Play className="w-3 h-3" />
                  <span>{running ? 'Running...' : 'Execute Script'}</span>
                </button>
              </div>
            </div>

            <pre className="p-4 bg-slate-950 rounded-lg text-xs font-mono text-slate-300 overflow-x-auto max-h-[360px] leading-relaxed border border-slate-800">
              <code>{currentScript.content}</code>
            </pre>
          </div>

          {/* Interactive Output Terminal */}
          <div className="bg-slate-950 border border-slate-800 rounded-xl p-5 space-y-2 font-mono">
            <div className="flex items-center justify-between pb-2 border-b border-slate-800 text-xs text-slate-400">
              <div className="flex items-center space-x-2">
                <Terminal className="w-3.5 h-3.5 text-emerald-400" />
                <span className="text-slate-300 font-semibold">Terminal Output</span>
              </div>
              <span>Status: {running ? 'Executing...' : output ? 'Finished (0)' : 'Idle'}</span>
            </div>

            <div className="p-3 bg-slate-900/60 rounded-lg text-xs text-slate-300 min-h-[100px] whitespace-pre-wrap leading-relaxed">
              {output || (
                <span className="text-slate-500 italic">
                  Click "Execute Script" above to simulate runner execution in container...
                </span>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
