import React, { useState, useEffect } from 'react';
import { Key, ShieldCheck, Copy, Check, Lock, RefreshCw, Terminal, Eye, EyeOff, AlertTriangle } from 'lucide-react';
import { AgentCredentials } from '../types';

const DEFAULT_CREDS: AgentCredentials = {
  appId: '1048291',
  installationId: '58392019',
  privateKey: '-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEA0rK1ZJ9r...[RSA PRIVATE KEY FOR GITHUB APP]...AgMBAAEC\n-----END RSA PRIVATE KEY-----',
  targetRepo: 'jbatt2026/AI-AGENTS',
  webhookSecret: 'whsec_98f3b6c7a1e42d8805f129c',
};

export const TokenAuthSimulator: React.FC = () => {
  const [creds, setCreds] = useState<AgentCredentials>(() => {
    const saved = localStorage.getItem('ai_agent_creds');
    return saved ? JSON.parse(saved) : DEFAULT_CREDS;
  });
  const [showKey, setShowKey] = useState(false);
  const [copiedToken, setCopiedToken] = useState(false);
  const [copiedHeader, setCopiedHeader] = useState(false);
  const [simulatedToken, setSimulatedToken] = useState<string>('');
  const [tokenTimeLeft, setTokenTimeLeft] = useState<number>(3600); // 60 minutes in seconds
  const [codeLang, setCodeLang] = useState<'node' | 'python' | 'curl'>('node');

  useEffect(() => {
    localStorage.setItem('ai_agent_creds', JSON.stringify(creds));
  }, [creds]);

  useEffect(() => {
    // Generate simulated token
    const hash = Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
    setSimulatedToken(`ghs_${hash}`);
    setTokenTimeLeft(3600);

    const timer = setInterval(() => {
      setTokenTimeLeft((prev) => (prev > 0 ? prev - 1 : 3600));
    }, 1000);

    return () => clearInterval(timer);
  }, [creds.installationId, creds.appId]);

  const handleRefreshSimToken = () => {
    const hash = Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
    setSimulatedToken(`ghs_${hash}`);
    setTokenTimeLeft(3600);
  };

  const formatTime = (seconds: number) => {
    const m = Math.floor(seconds / 60);
    const s = seconds % 60;
    return `${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
  };

  const getNodeSnippet = () => `import { Octokit } from "@octokit/rest";
import { createAppAuth } from "@octokit/auth-app";

// Authenticate as the GitHub App Installation
const octokit = new Octokit({
  authStrategy: createAppAuth,
  auth: {
    appId: ${creds.appId || 'process.env.GITHUB_APP_ID'},
    privateKey: process.env.GITHUB_APP_PRIVATE_KEY,
    installationId: ${creds.installationId || 'process.env.GITHUB_APP_INSTALLATION_ID'},
  },
});

// Example: Create branch and open Pull Request for AI agent
async function createAgentPR() {
  const [owner, repo] = "${creds.targetRepo}".split("/");
  
  // 1. Get base branch commit SHA
  const { data: ref } = await octokit.rest.git.getRef({
    owner,
    repo,
    ref: "heads/main",
  });
  
  // 2. Create agent branch
  const branchName = "agent/claude-security-patch";
  await octokit.rest.git.createRef({
    owner,
    repo,
    ref: \`refs/heads/\${branchName}\`,
    sha: ref.object.sha,
  });

  // 3. Open PR
  const pr = await octokit.rest.pulls.create({
    owner,
    repo,
    title: "feat(security): update dependency locks and audit checks",
    head: branchName,
    base: "main",
    body: "Automated patch generated by AI Agent.\\n\\n> Generated with [Claude Code](https://claude.ai/code)",
  });

  console.log(\`PR created: \${pr.data.html_url}\`);
}`;

  const getPythonSnippet = () => `import os
import jwt
import time
import requests

# 1. Generate JWT signed with GitHub App Private Key
def generate_jwt(app_id, private_key_pem):
    now = int(time.time())
    payload = {
        "iat": now - 60,
        "exp": now + (10 * 60),
        "iss": str(app_id)
    }
    return jwt.encode(payload, private_key_pem, algorithm="RS256")

# 2. Exchange JWT for short-lived Installation Access Token
def get_installation_token(jwt_token, installation_id):
    headers = {
        "Authorization": f"Bearer {jwt_token}",
        "Accept": "application/vnd.github+json"
    }
    res = requests.post(
        f"https://api.github.com/app/installations/{installation_id}/access_tokens",
        headers=headers
    )
    return res.json()["token"]

# 3. Use Token with GitHub REST API
installation_token = get_installation_token(
    generate_jwt("${creds.appId}", os.environ["GITHUB_APP_PRIVATE_KEY"]),
    "${creds.installationId}"
)
print(f"Token obtained: {installation_token[:10]}...")`;

  const getCurlSnippet = () => `# Step 1: Request an installation access token using your signed JWT
curl -X POST \\
  -H "Authorization: Bearer YOUR_GENERATED_JWT" \\
  -H "Accept: application/vnd.github+json" \\
  https://api.github.com/app/installations/${creds.installationId}/access_tokens

# Step 2: Use the installation token to open an Agent PR
curl -X POST \\
  -H "Authorization: Bearer ${simulatedToken}" \\
  -H "Accept: application/vnd.github+json" \\
  https://api.github.com/repos/${creds.targetRepo}/pulls \\
  -d '{
    "title": "refactor: optimize build script bundle size",
    "head": "agent/claude-perf-tuning",
    "base": "main",
    "body": "Automated performance improvements.\\n\\n> Generated with Claude Code"
  }'`;

  const codeContent =
    codeLang === 'node' ? getNodeSnippet() : codeLang === 'python' ? getPythonSnippet() : getCurlSnippet();

  return (
    <div className="space-y-6">
      {/* Overview Banner */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-sm">
        <div className="flex items-center space-x-3">
          <ShieldCheck className="w-6 h-6 text-emerald-400" />
          <div>
            <h2 className="text-lg font-bold text-white">Agent Authentication & Token Generator</h2>
            <p className="text-sm text-slate-400 mt-1">
              Verify your GitHub App credentials, inspect JSON Web Tokens (JWT) and short-lived Installation Access Tokens used by agent runners.
            </p>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Column: Credentials & Token Status */}
        <div className="lg:col-span-6 space-y-6">
          {/* Active Installation Token Card */}
          <div className="bg-gradient-to-br from-slate-900 to-slate-950 border border-slate-800 rounded-xl p-5 relative overflow-hidden shadow-md">
            <div className="flex items-center justify-between pb-3 border-b border-slate-800">
              <div className="flex items-center space-x-2">
                <Key className="w-4 h-4 text-emerald-400" />
                <span className="text-xs font-semibold uppercase tracking-wider text-slate-200">
                  Installation Access Token (Simulation)
                </span>
              </div>
              <button
                onClick={handleRefreshSimToken}
                title="Regenerate token"
                className="p-1.5 rounded-md hover:bg-slate-800 text-slate-400 hover:text-slate-200 transition-colors"
              >
                <RefreshCw className="w-3.5 h-3.5" />
              </button>
            </div>

            <div className="mt-4 p-3.5 bg-slate-950 rounded-lg border border-slate-800 flex items-center justify-between">
              <div className="font-mono text-sm text-emerald-400 font-semibold truncate mr-2">
                {simulatedToken}
              </div>
              <button
                onClick={() => {
                  navigator.clipboard.writeText(simulatedToken);
                  setCopiedToken(true);
                  setTimeout(() => setCopiedToken(false), 2000);
                }}
                className="px-2.5 py-1 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded text-xs font-medium inline-flex items-center space-x-1 shrink-0 transition-colors"
              >
                {copiedToken ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                <span>{copiedToken ? 'Copied' : 'Copy'}</span>
              </button>
            </div>

            <div className="mt-4 grid grid-cols-3 gap-2 text-center">
              <div className="p-2.5 rounded-lg bg-slate-950/60 border border-slate-800/80">
                <span className="text-[10px] uppercase text-slate-400 block font-semibold">Scope</span>
                <span className="text-xs font-semibold text-blue-400">Read & Write</span>
              </div>
              <div className="p-2.5 rounded-lg bg-slate-950/60 border border-slate-800/80">
                <span className="text-[10px] uppercase text-slate-400 block font-semibold">Repository</span>
                <span className="text-xs font-semibold text-slate-200 truncate block">{creds.targetRepo}</span>
              </div>
              <div className="p-2.5 rounded-lg bg-slate-950/60 border border-slate-800/80">
                <span className="text-[10px] uppercase text-slate-400 block font-semibold">Expires In</span>
                <span className="text-xs font-semibold text-emerald-400 font-mono">{formatTime(tokenTimeLeft)}</span>
              </div>
            </div>
          </div>

          {/* Credentials Form */}
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-4">
            <div className="flex items-center justify-between">
              <h3 className="text-sm font-semibold text-slate-200 uppercase tracking-wider">
                App & Target Config
              </h3>
              <div className="flex items-center space-x-1 text-[11px] text-amber-400">
                <Lock className="w-3 h-3" />
                <span>Stored in Local State</span>
              </div>
            </div>

            <div className="space-y-3">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-medium text-slate-400 mb-1">
                    GitHub App ID
                  </label>
                  <input
                    type="text"
                    value={creds.appId}
                    onChange={(e) => setCreds({ ...creds, appId: e.target.value })}
                    className="w-full bg-slate-950 border border-slate-700 rounded-lg px-3 py-2 text-xs text-slate-100 font-mono focus:outline-none focus:border-blue-500"
                    placeholder="e.g. 123456"
                  />
                </div>

                <div>
                  <label className="block text-xs font-medium text-slate-400 mb-1">
                    Installation ID
                  </label>
                  <input
                    type="text"
                    value={creds.installationId}
                    onChange={(e) => setCreds({ ...creds, installationId: e.target.value })}
                    className="w-full bg-slate-950 border border-slate-700 rounded-lg px-3 py-2 text-xs text-slate-100 font-mono focus:outline-none focus:border-blue-500"
                    placeholder="e.g. 98765432"
                  />
                </div>
              </div>

              <div>
                <label className="block text-xs font-medium text-slate-400 mb-1">
                  Target Repository
                </label>
                <input
                  type="text"
                  value={creds.targetRepo}
                  onChange={(e) => setCreds({ ...creds, targetRepo: e.target.value })}
                  className="w-full bg-slate-950 border border-slate-700 rounded-lg px-3 py-2 text-xs text-slate-100 font-mono focus:outline-none focus:border-blue-500"
                  placeholder="owner/repo (e.g. jbatt2026/AI-AGENTS)"
                />
              </div>

              <div>
                <div className="flex items-center justify-between mb-1">
                  <label className="text-xs font-medium text-slate-400">
                    Private Key (.pem) Mask
                  </label>
                  <button
                    type="button"
                    onClick={() => setShowKey(!showKey)}
                    className="text-[11px] text-blue-400 hover:text-blue-300 inline-flex items-center space-x-1"
                  >
                    {showKey ? <EyeOff className="w-3 h-3" /> : <Eye className="w-3 h-3" />}
                    <span>{showKey ? 'Hide Key' : 'Reveal Key'}</span>
                  </button>
                </div>
                <textarea
                  rows={3}
                  value={creds.privateKey}
                  onChange={(e) => setCreds({ ...creds, privateKey: e.target.value })}
                  className={`w-full bg-slate-950 border border-slate-700 rounded-lg p-2.5 text-xs text-slate-300 font-mono focus:outline-none focus:border-blue-500 ${
                    !showKey ? 'blur-[2px]' : ''
                  }`}
                  placeholder="-----BEGIN RSA PRIVATE KEY-----"
                />
              </div>
            </div>

            {/* Warning rule */}
            <div className="p-3 bg-amber-500/10 border border-amber-500/20 rounded-lg flex items-start space-x-2 text-xs text-amber-300">
              <AlertTriangle className="w-4 h-4 shrink-0 mt-0.5" />
              <p>
                <strong>Security Rule:</strong> Never commit your private key (<code className="text-amber-200 font-mono">.pem</code>) into the git repository. Inject it via <code className="text-amber-200 font-mono">GITHUB_APP_PRIVATE_KEY</code> in environment variables or GitHub Secrets.
              </p>
            </div>
          </div>
        </div>

        {/* Right Column: Code Snippets & Auth Integrations */}
        <div className="lg:col-span-6 space-y-4">
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 sticky top-20">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pb-3 border-b border-slate-800">
              <div className="flex items-center space-x-2">
                <Terminal className="w-4 h-4 text-blue-400" />
                <span className="text-xs font-semibold text-slate-200 uppercase tracking-wider">
                  Agent Authentication Code
                </span>
              </div>

              {/* Language Selector */}
              <div className="flex items-center space-x-1 bg-slate-950 p-1 rounded-lg border border-slate-800">
                {(['node', 'python', 'curl'] as const).map((lang) => (
                  <button
                    key={lang}
                    onClick={() => setCodeLang(lang)}
                    className={`px-2.5 py-1 rounded text-xs font-medium transition-colors ${
                      codeLang === lang
                        ? 'bg-blue-600 text-white shadow-sm'
                        : 'text-slate-400 hover:text-slate-200'
                    }`}
                  >
                    {lang === 'node' ? 'Node.js' : lang === 'python' ? 'Python' : 'cURL'}
                  </button>
                ))}
              </div>
            </div>

            <pre className="mt-3 p-4 bg-slate-950 rounded-lg text-xs font-mono text-slate-300 overflow-x-auto max-h-[460px] leading-relaxed border border-slate-800">
              <code>{codeContent}</code>
            </pre>

            <div className="mt-3 flex items-center justify-end">
              <button
                onClick={() => {
                  navigator.clipboard.writeText(codeContent);
                  setCopiedHeader(true);
                  setTimeout(() => setCopiedHeader(false), 2000);
                }}
                className="inline-flex items-center space-x-1.5 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-medium rounded-lg border border-slate-700 transition-colors"
              >
                {copiedHeader ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedHeader ? 'Copied Code!' : 'Copy Code'}</span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
